import assert from 'node:assert/strict';
import {GameAudio} from '../dist/game-audio.js';
import {initialState} from '../dist/city-data.js';
import {vehicleById} from '../dist/fleet-data.js';
const param=()=>({value:0,setTargetAtTime(v){this.value=v},setValueAtTime(v){this.value=v},exponentialRampToValueAtTime(v){this.value=v}});
const node=()=>({gain:param(),frequency:param(),Q:param(),threshold:param(),knee:param(),ratio:param(),connect(){return this},disconnect(){},start(){},stop(){}});
let builds=0;class AudioContext{constructor(){builds++;this.state='suspended';this.sampleRate=8000;this.currentTime=0;this.destination=node()}createGain(){return node()}createDynamicsCompressor(){return node()}createOscillator(){return node()}createBiquadFilter(){return node()}createBufferSource(){return node()}createBuffer(c,n){return{getChannelData:()=>new Float32Array(n)}}createAnalyser(){return{...node(),getByteTimeDomainData(a){a.fill(128)}}}resume(){this.state='running';return Promise.resolve()}}
const statuses=[],audio=new GameAudio(s=>statuses.push(s),AudioContext);assert.equal(builds,0);assert(await audio.unlock());assert.equal(builds,1);assert.equal(audio.status,'on');const s=initialState();s.phase='playing';s.mode='bike';s.speed=18;s.throttle=1;audio.update(s,vehicleById('vanta'));assert(audio.motorGain.gain.value>0);const bikePitch=audio.motor.frequency.value;audio.update(s,vehicleById('brutus'));assert(audio.motor.frequency.value<bikePitch);audio.update(s,vehicleById('aether'));assert(audio.whineGain.gain.value>.05);s.braking=1;s.boosting=true;audio.update(s,vehicleById('aether'));assert(audio.brakeGain.gain.value>0);assert(audio.boostGain.gain.value>0);audio.setVolume(.25);audio.update(s,vehicleById('aether'));assert.equal(audio.master.gain.value,.25);await audio.setEnabled(false);audio.update(s);assert.equal(audio.master.gain.value,0);await audio.setEnabled(true);assert.equal(builds,1);s.phase='paused';audio.update(s);assert.equal(audio.motorGain.gain.value,0);assert.equal(audio.ambientGain.gain.value,0);
class Blocked extends AudioContext{resume(){return Promise.reject(new Error('NotAllowed'))}}const blocked=new GameAudio(()=>{},Blocked);assert.equal(await blocked.unlock(),false);assert.equal(blocked.status,'blocked');
console.log('PASS: gesture-only creation, unlock, engine classes, throttle, braking, boost, volume, mute/unmute, pause silence, blocked-autoplay recovery state.');
